client_config_backend: settings
client_config:
  client_id: 504245679417-ovh9vkt454j9fiidufsscl88t6pocd0r.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive